### ISSUE TITLE
Make a tutorial on how to use the coap node

### ISSUE THREAD

**Issue by reederz** [JKRhb/node-red-contrib-coap#1]

**Comment by dashingsuma** [comment]
I am trying to create a client server same as in examples just with POST method could you please help!

**Comment by reederz** [comment]
@dashingsuma I'm not working on this project actively. If you figure out what's missing in examples, I'll happily consider a pull request.

**Comment by dashingsuma** [comment]
Hi thank you for replying, Your example is perfectly working  for GET Method I am just not able to figure it out how to use it  for POST method
