### ISSUE TITLE
resending confirmable messages

### ISSUE THREAD

**Issue by fero29** [JKRhb/node-red-contrib-coap#14]
When I send CON message to any node although comes response (and I send ack) but my node resend mesage as if dont came response.

**Comment by GwenStouthuysen** [comment]
I don't understand exactly what you want.
Do you know how CoAP functions?
Following a CON message, It is intended to send back an acknowledgment, to confirm the receival of the message.
If the actual command is executed, it is intended to send back the token too, so that the sended has the confirmation that his command has been executed.
This is somehow missing in this implementation.
If you set up a server, it nicely sends back the ACK message with the id, but it does not send back the token. So the sender is waiting for that confirmation, this blocks the senders process.

This has to be implemented somehow (a feedback node that you can pass the original tooken to so the server knows it can send the token, with the response, to close the request.

**Comment by JKRhb** [comment]
Thank you for your comment, @GwenStouthuysen! I am currently working on a response node (similar to the HTTP one, see issue #20) where this behavior should also be included.

**Comment by GwenStouthuysen** [comment]
Jan,

I use NodeRed to demonstrate simple IoT networking systems to students.
We monitored the communication with Wireshark and there I realized why the
coap-cli task did not conclude when sending a put or post command.

Regards,

Gwen

Op do 4 feb. 2021 om 21:15 schreef Jan Romann <notifications@github.com>:

**Comment by JKRhb** [comment]
> 
> Jan, I use NodeRed to demonstrate simple IoT networking systems to students. We monitored the communication with Wireshark and there I realized why the coap-cli task did not conclude when sending a put or post command. 

Thanks once again for your feedback! Did you use a function node calling `msg.res.end("foo")` to send the response? If not, could you post your flow setup for reproducing the problem?

I would ping you once I have finshed a first version of the reponse node implementation, maybe you can have a look at it :)

**Comment by GwenStouthuysen** [comment]
This worked.

Where was this documented ?

Here is the flow I created to handle put requests to drive an output.
[{"id":"112b1d56.494243","type":"tab","label":"Flow
2","disabled":false,"info":""},{"id":"b93956b8.47de08","type":"coap
in","z":"112b1d56.494243","method":"PUT","name":"","server":"a9e9f5a9.2d3428","url":"/licht","x":140,"y":180,"wires":[["e5a5fa9b.8a24a8"]]},{"id":"e5a5fa9b.8a24a8","type":"function","z":"112b1d56.494243","name":"","func":"if(msg.req.payload[0]
== 0x31){\n    msg.payload = 1;\n}else{\n    msg.payload =
0;\n}\nmsg.res.end(\"foo\");\nreturn
msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":360,"y":240,"wires":[["245b46f2.6b2dfa"]]},{"id":"245b46f2.6b2dfa","type":"debug","z":"112b1d56.494243","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":560,"y":260,"wires":[]},{"id":"a9e9f5a9.2d3428","type":"coap-server","name":"server","port":"5683","ipv6":true}]

Replace the debug node with a GPIO port and you will be able to drive the
output on by sending a "1" to the coap instance

This failing documentation is the biggest downside of Node Red: you can do
a lot but nobody tells us how.
All demo's are basic, where the tricks are in the details to make the next
step work.

Gwen

Op vr 5 feb. 2021 om 09:55 schreef Jan Romann <notifications@github.com>:

**Comment by JKRhb** [comment]
> 
> This worked. 

That is great :) I was worrying that this might be an issue with the underlying `node-coap` package but it is good to hear that this version works. By calling `end` on the response object (`res`) the server is sending the actual response to a request. You can omit the input or insert the payload that should be transmitted (by replacing the "foo"). As I mentioned, this is only provisional, I am working on a more intuitive solution that is more similar to existing nodes. Sorry for the inconvenience this has caused you :/ I am glad, however, that the problem could be solved for now.

>Where was this documented 

Unfortunately, this has not been documented so far. I only found it out by chance before when I started working with the package. I hope that this workaround soon won't be necessary anymore. However, I will add more documentation to the package in general.

> This failing documentation is the biggest downside of Node Red: you can do a lot but nobody tells us how. All demo's are basic, where the tricks are in the details to make the next step work.

You are right, it depends a lot on the resource and effort maintainers and contributors can put into a package or the project as a whole. But feedback like yours is equally important for pointing out existing flaws and things that can be improved upon to change things for the better :)

**Comment by JKRhb** [comment]
I would consider this issue resolved for now, feel free to comment on this if any problems should persist, though :)
