### ISSUE TITLE
COAP request node not working on BeagleBone

### ISSUE THREAD

**Issue by MichalPoterek** [JKRhb/node-red-contrib-coap#40]
Hi, looks like udp6 checkboks with version 0.6 is working for COAP server but   coap request node is not active on pallete. I haven't got any errors during installation. How to track this kind of issue?

**Comment by JKRhb** [comment]
Hmm, can you give me more information? Do you get some kind of error message?

**Comment by JKRhb** [comment]
Or could you maybe export your flow and post it here so that I can reproduce the issue?

**Comment by MichalPoterek** [comment]
![image](https://user-images.githubusercontent.com/67839947/143486348-0e180f81-e7cb-49d4-b5a3-c6cb10995d99.png)
On the Manage pallete   Coap request node is not active.  When I try to filter  Coap request on left sidebar its not shown
![image](https://user-images.githubusercontent.com/67839947/143486567-ea07f458-9212-4a86-8a7f-40f7ab6af45a.png)

**Comment by JKRhb** [comment]
Thank you! I'll have a look into it and will provide a fix as soon as possible.

**Comment by MichalPoterek** [comment]
Below you can see how I did installation
![image](https://user-images.githubusercontent.com/67839947/143486793-9ceb915b-4ef0-4d53-b3e7-0c796d54c5c2.png)

**Comment by MichalPoterek** [comment]
I did a test and I have removed node-red-contrib-coap with use Manage palette and I install node-red-contrib-coap with Manage palette as well. And it looks like problem is exactly the same -  Coap request is not active.

**Comment by JKRhb** [comment]
Hmm, that is weird. I installed the new version on a different machine now and the request node appears in the palette :/ Not sure where the problem is. Do you get a log message regarding the missing node?

**Comment by MichalPoterek** [comment]
Please find below view log from Manage palette. You can see I removed node-red-contrib-coap and installed it once again. What I can check additionally? Maybe some software version of dependencies - if yes then which?

-----------------------------------------------------------
2021-11-25T18:56:37.385Z Remove : node-red-contrib-coap

2021-11-25T18:56:37.427Z npm remove --no-audit --no-update-notifier --no-fund --save node-red-contrib-coap
2021-11-25T18:57:00.850Z [out] removed 6 packages in 14.585s
2021-11-25T18:57:02.230Z rc=0

-----------------------------------------------------------
2021-11-25T18:57:31.011Z Install : node-red-contrib-coap 0.6.0

2021-11-25T18:57:30.920Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-coap@0.6.0
2021-11-25T18:58:00.596Z [out] + node-red-contrib-coap@0.6.0
2021-11-25T18:58:00.596Z [out] added 6 packages from 8 contributors in 22.851s
2021-11-25T18:58:01.960Z rc=0

**Comment by JKRhb** [comment]
Do you get an error when you restart node-red and it says something like "Node `coap-request` missing"?

**Comment by MichalPoterek** [comment]
No, I can see coap -request is missing only when I go and try fo search for it on left toolbar or if I go take a look on Manage palette.   May I ask you what version of npm you are using?

**Comment by JKRhb** [comment]
I am using node 14 and 15, and npm 7. Which version are you using? Also, which node-red version do you have installed?

**Comment by MichalPoterek** [comment]
So I was using npm 6.13.4  and Node.js 10.18   I'm just during upgrade to newest versions - I will let you know it it help

**Comment by MichalPoterek** [comment]
Finally I found something interesting
Nov 25 20:49:33 beaglebone Node-RED[2116]: 25 Nov 20:49:33 - [info] Installed module: node-red-contrib-coap
Nov 25 20:49:35 beaglebone Node-RED[2116]: 25 Nov 20:49:35 - [info] Added node types:
Nov 25 20:49:35 beaglebone Node-RED[2116]: 25 Nov 20:49:35 - [info]  - node-red-contrib-coap:coap-server
Nov 25 20:49:35 beaglebone Node-RED[2116]: 25 Nov 20:49:35 - [info]  - node-red-contrib-coap:coap in
Nov 25 20:49:35 beaglebone Node-RED[2116]: 25 Nov 20:49:35 - [info]  - node-red-contrib-coap:coap request : ReferenceError: TextDecoder is not defined

**Comment by JKRhb** [comment]
Thank you for the update! This seems to actually be related to the node version: https://discourse.nodered.org/t/referenceerror-textdecoder-is-not-defined-in-smartnora-update/50857/2 But you said that you are already using node version 12, right?

**Comment by MichalPoterek** [comment]
So I propably doing something wrong. Yes I update  Node.js but when I'm   putting  n -V   I see   version 8
root@beaglebone:/home/c# sudo n 15
  installing : node-v15.14.0
       mkdir : /usr/local/n/versions/node/15.14.0
       fetch : https://nodejs.org/dist/v15.14.0/node-v15.14.0-linux-armv7l.tar.xz
   installed : v15.14.0 (with npm 7.7.6)
root@beaglebone:/home/c# n -V
v8.0.0

**Comment by JKRhb** [comment]
Maybe there is preinstalled node package (the version 8 one) which needs to be uninstalled first? I think this is a problem in some Linux distributions where the provided packages are outdated.

**Comment by MichalPoterek** [comment]
It's looks like pure problem with Node.js   From different reasons  I need to stick with the current version of beaglebone buster Linux distribution. I have downgraded to 0.42 versions and will work with that. With   n   it was possible to install newer versions without problem and when I put command  node -v   it give me newest version installed but when I place command n -V it was showing 8.0.0    It might be that special configuration/linking need to be done (but I haven't found that anybody provide how it should be done for beaglebone distribution).  Maybe somebody was updating already Node.js  and can give me some hints?

**Comment by MichalPoterek** [comment]
Hi, looks like problem is more complicated. 
I'm using now latest  Beaglebone image https://debian.beagleboard.org/images/bone-debian-10.3-iot-armhf-2020-04-06-4gb.img.xz


I was trying to install node-red-contrib-coap 0.6 through web gui and  command line but both ways not working for me :(

Thats what I found in log:
![image](https://user-images.githubusercontent.com/67839947/161381158-bba35832-5de1-4a0a-ae2e-8b0d763e1ebb.png)

This is console output during installing coap manually
root@beaglebone:/home/c# cd /var/lib/node-red/.node-red/node_modules
root@beaglebone:/var/lib/node-red/.node-red/node_modules# git clone https://github.com/JKRhb/node-red-contrib-coap.git
Cloning into 'node-red-contrib-coap'...
remote: Enumerating objects: 783, done.
remote: Counting objects: 100% (266/266), done.
remote: Compressing objects: 100% (164/164), done.
remote: Total 783 (delta 156), reused 188 (delta 101), pack-reused 517
Receiving objects: 100% (783/783), 477.52 KiB | 1.37 MiB/s, done.
Resolving deltas: 100% (449/449), done.
root@beaglebone:/var/lib/node-red/.node-red/node_modules# cd node-red-contrib-coap/
root@beaglebone:/var/lib/node-red/.node-red/node_modules/node-red-contrib-coap# sudo npm install
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN notice [SECURITY] ansi-regex has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=ansi-regex - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] shelljs has the following vulnerabilities: 1 high, 1 moderate. Go here for more details: https://github.com/advisories?query=shelljs - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] path-parse has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=path-parse - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] browserslist has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=browserslist - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] node-fetch has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=node-fetch - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] nanoid has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=nanoid - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] json-schema has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=json-schema - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] hosted-git-info has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=hosted-git-info - Run `npm i npm@latest -g`
to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] axios has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=axios - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] follow-redirects has the following vulnerabilities: 1 high, 1 moderate. Go here for more details: https://github.com/advisories?query=follow-redirects - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> bcrypt@5.0.1 install /var/lib/node-red/.node-red/node_modules/node-red-contrib-coap/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-arm-glibc.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@5.0.1 and node@10.24.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-arm-glibc.tar.gz
make: Entering directory '/var/lib/node-red/.node-red/node_modules/node-red-contrib-coap/node_modules/bcrypt/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
  COPY /var/lib/node-red/.node-red/node_modules/node-red-contrib-coap/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/var/lib/node-red/.node-red/node_modules/node-red-contrib-coap/node_modules/bcrypt/build'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

added 620 packages from 932 contributors in 358.67s


Even if this installation went well  there is no coap request node (coap in is avaiable)
![image](https://user-images.githubusercontent.com/67839947/161381270-fb41d0e9-6eca-4fca-a87e-ceaf736053de.png)

I have tested, installing other modules for node-red not making any problems
![image](https://user-images.githubusercontent.com/67839947/161381308-78596da3-fab9-4eb3-b509-52587394ae7f.png)

I will be appriciated for any guidance what to check and how to check whats cousing a problem

**Comment by JKRhb** [comment]
Hmm, there seems to be an error related to TextEncoder. I will have a look into it. Maybe it does work with node versions below 12?

**Comment by JKRhb** [comment]
I just added node version 10 to the CI pipeline and the issue in fact related to the outdated version: https://github.com/JKRhb/node-red-contrib-coap/runs/5799903954?check_suite_focus=true Updating your node version to at least 12 (which is actually also end-of-life by the end of this month) should therefore fix the problem :)

**Comment by MichalPoterek** [comment]
nodejs -v
v10.24.0

**Comment by JKRhb** [comment]
> nodejs -v v10.24.0

Hm, yeah, this version needs to be at least v12.0.0

**Comment by JKRhb** [comment]
Have you tried out this yet? https://nodered.org/docs/getting-started/beaglebone

**Comment by MichalPoterek** [comment]
Yes I was trying it. I will upgrade Buster to Bullseye as it has nodejs v12 and I will let you know

**Comment by MichalPoterek** [comment]
Finally I have made id working 
![image](https://user-images.githubusercontent.com/67839947/161395729-359943d7-9e25-472a-84d2-78d1593497d6.png)

I upgraded clean Beaglebone Buster to Bullseye

To do that you need to:
add below to /etc/apt/sources.list 

deb http://deb.debian.org/debian/ bullseye main contrib non-free
#deb-src http://deb.debian.org/debian/ bullseye main contrib non-free

deb http://security.debian.org/debian-security bullseye-security main contrib non-free
#deb-src http://security.debian.org/debian-security bullseye-security main contrib non-free

deb http://deb.debian.org/debian bullseye-updates main contrib non-free
#deb-src http://deb.debian.org/debian bullseye-updates main contrib non-free

deb [arch=armhf] http://repos.rcn-ee.com/debian/ bullseye main
#deb-src [arch=armhf] http://repos.rcn-ee.com/debian/ bullseye main 



and then 
sudo apt dist-upgrade -y

Whenever I was asked I kept old config files.  After reboot all works well. I hope my long time to find out how to make it working help others :)

**Comment by MichalPoterek** [comment]
One more thing in some cases you need to enable node-red service at boot
systemctl enable nodered.service

**Comment by JKRhb** [comment]
@MichalPoterek Awesome that you could make it work! And thank you for posting the instructions of how you did it :)

**Comment by JKRhb** [comment]
@MichalPoterek I opened #49 to include some information regarding the issue in the README :) After merging, I think we should be able to close this issue as users will be able to find your instructions in the future :)
