### ISSUE TITLE
NONCONfirmable message missing option

### ISSUE THREAD

**Issue by SalarJamal** [JKRhb/node-red-contrib-coap#63]
I'm using a CoAP request node to send message to a coap-server hosted on a distant machine. I can't find the way to choose NONCON (non confirmable) option.

**Comment by JKRhb** [comment]
Thank you, @SalarJamal, I think this feature is currently not supported yet (at the moment, all messages are confirmable). I'll add an option to make this behavior configurable.

**Comment by SalarJamal** [comment]
Thank you Mr. @JKRhb

**Comment by JKRhb** [comment]
I added the feature in #78 and will release a new version shortly :)
